### PR TITLE
Update parser.rb

### PR DESCRIPTION
**Pull request by lahiruj**
Removed require 'crack' and Crack::JSON.parse(body) replaced only with json

### CODE REVIEW

**Comment by ramdesh** [comment]
Seems like a pretty straightforward update, has this been pulled in yet?

**Comment by lahiruj** [comment]
Nope not yet. :)

**Comment by ramdesh** [comment]
Maybe it's time to bug someone. :smile:

**Comment by lahiruj** [comment]
:D Yeap. But the problem is this wrapper can't deliver all requirements of the new bridge. :) So left it there. Had to take alternative paths. ;)

**Pull request merged**
